TEST=test25_random_tasks
all: $(TEST) kernel.ptx kernel.openmp.so kernel.hip

include ../Makefile.tests

kernel.openmp.so: kernel.openmp.c
	$(CC) -g -lgomp -Wl,-rpath=$(OPENMP_PATH) -fPIC -shared -I. $(CFLAGS) -o $@ $^

clean:
	rm -f kernel.ptx kernel.hip kernel.openmp.so test25_random_tasks
