#!/bin/bash
if [ ! -n "$IRIS_INSTALL_ROOT" ]; then
	IRIS_INSTALL_ROOT="$HOME/.local"
fi
rm -rf build
mkdir build
cd build
CC=gcc
CXX=g++
#FC=gfortran
#cmake .. -DCMAKE_INSTALL_PREFIX=$IRIS_INSTALL_ROOT -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_FC_COMPILER=$FC -DCMAKE_BUILD_TYPE=DEBUG -DUSE_PYTHON=ON -DUSE_FORTRAN=ON
cmake .. -DCMAKE_INSTALL_PREFIX=$IRIS_INSTALL_ROOT -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=DEBUG -DCOVERAGE=true
#cmake .. -DCMAKE_INSTALL_PREFIX=$IRIS_INSTALL_ROOT -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=RELEASE
make -j install

#export CPATH=$CPATH:$IRIS_INSTALL_ROOT/include
#export LIBRARY_PATH=$LIBRARY_PATH:$IRIS_INSTALL_ROOT/lib64

