#!/bin/bash
if [ ! -n "$IRIS_INSTALL_ROOT" ]; then
	IRIS_INSTALL_ROOT="$HOME/.iris"
fi
rm -rf build
mkdir build
cd build
CC=gcc
CXX=g++
#FC=gfortran
cmake .. -DCMAKE_INSTALL_PREFIX=$IRIS_INSTALL_ROOT -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=DEBUG -DTRACE_DISABLE=ON
#cmake .. -DCMAKE_INSTALL_PREFIX=$IRIS_INSTALL_ROOT -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=RELEASE -DUSE_PYTHON=ON -DUSE_FORTRAN=ON
make -j install

