#!/bin/bash
if [ ! -n "$IRIS_INSTALL_ROOT" ]; then
	IRIS_INSTALL_ROOT="$HOME/.iris"
fi
if [ ! -n "$IRIS_TAG" ]; then
IRIS_TAG=
fi
if [ ! -n "$BUILD_DIR" ]; then
    BUILD_DIR=build
fi
BUILD_TYPE=${BUILD_TYPE:-RELEASE}
BUILD_DIR_NAME=${BUILD_DIR}${IRIS_TAG}
rm -rf $BUILD_DIR_NAME
mkdir -p $BUILD_DIR_NAME
cd $BUILD_DIR_NAME
CC=gcc
CXX=g++
#FC=gfortran
cmake -G "Ninja" .. $@ \
  -DCMAKE_GENERATOR:INTERNAL=Ninja                        \
  -DCMAKE_INSTALL_PREFIX=${IRIS_INSTALL_ROOT}${IRIS_TAG}  \
  -DCMAKE_C_COMPILER=$CC      \
  -DCMAKE_CXX_COMPILER=$CXX   \
  -DCMAKE_BUILD_TYPE=RELEASE  \
  -DTRACE_DISABLE=ON  \
  -DDEBUG_DISABLE=ON  \
  -DINFO_DISABLE=ON   \
  -DCHECK_DISABLE=ON  \
  -DTODO_DISABLE=ON   \
  -DWARNING_DISABLE=ON\
  -DAUTO_PARALLEL=ON  \
  -DAUTO_FLUSH=ON     
  #-DUSE_PYTHON=ON     \
  #-DUSE_FORTRAN=ON    \

#cmake .. -DCMAKE_INSTALL_PREFIX=${IRIS_INSTALL_ROOT} -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DTRACE_DISABLE=ON -DDEBUG_DISABLE=ON
#cmake .. -DCMAKE_INSTALL_PREFIX=$IRIS_INSTALL_ROOT -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=RELEASE -DTRACE_DISABLE=ON
#cmake .. -DCMAKE_INSTALL_PREFIX=$IRIS_INSTALL_ROOT -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=RELEASE -DUSE_PYTHON=ON -DUSE_FORTRAN=ON
# make -j install
ninja install
