[tool.project]
name = "iris"
version = "3.0"
description = "IRIS project with CMake build"
authors = ["Narasinga Rao Miniskar <miniskarnr@ornl.gov>"]

[build-system]
requires = ["setuptools>=42", "wheel", "cmake"]
build-backend = "setuptools.build_meta"
