#!/bin/bash

rm -rf                                                    \
  ./build                                                 \
  ./*/kernel.ptx                                          \
  ./*/kernel.hip                                          \
  ./*/kernel.openmp.so                                    \
  ./*/kernel.nvopenmp.so                                  \
  ./01_init_finalize/test01_init_finalize                 \
  ./02_task_depend/test02_task_depend                     \
  ./03_release/test03_release                             \
  ./04_enclosing_targets/test04_enclosing_targets         \
  ./06_device/test06_device                               \
  ./07_policy_register/test07_policy_register             \
  ./07_policy_register/libPolicyGWSHook.so                \
  ./07_policy_register/libPolicyGWS.so                    \
  ./07_policy_register/policy_last.so                     \
  ./08_multithreading/test08_multithreading               \
  ./09_dataflow/test09_dataflow                           \
  ./10_multikernelexecution/test10_multikernelexecution   \
  ./11_deadlock/test11_deadlock                           \
  ./12_task_custom/test12_task_custom                     \
  ./13_hooks/test13_hooks                                 \
  ./14_permanent_task/test14_permanent_task               \
  ./15_graph/test15_graph                                 \
  ./16_task_host/test16_task_host                         \
  ./17_json/test17_json                                   \
  ./18_record/test18_record                               \
  ./18_record/*.json                                      \
  ./19_replay/test19_replay                               \
  ./19_replay/*.json                                      \
  ./20_cublas/test20_cublas                               \
  ./21_task_malloc/test21_task_malloc                     \
  ./22_json_mixed_args/test22_json_mixed_args             \
  ./23_multigraph/test23_multigraph                       \
  ./24_multi_kernels/test24_multi_kernels                 \
  ./25_random_tasks/test25_random_tasks                   \
  ./26_env_set/test26_env_set                             \
  ./27_deadlock2/test27_deadlock2                         \
  ./28_json2/test28_json2                                 \
  ./29_data_mem/test29_data_mem                           \
  ./30_task_info/test30_task_info                         \
  ./32_json3/test32_json3                                 \
  ./33_graph_cpp/test33_graph_cpp                         \
  ./33_graph_cpp/*.so                                     \
  ./34_set_mem/test34_set_mem                             \
  ./35_json_mixed_args_record_replay/test35_json_mixed_args_record_replay \
  ./36_double_json_mixed_args_record_replay/test36_double_json_mixed_args_record_replay  \
  ./37_opencl_icd/test37_opencl_icd                      \
  ./38_offset/test38_offset                              \
  **/*.ptx                                                

rm -rf ./35_json_mixed_args_record_replay/*.csv  \
       ./34_set_mem/*.csv \
       ./30_task_info/*.csv \
       ./32_json3/*.csv \
       ./38_offset/*.csv \
       ./33_graph_cpp/*.csv \
       ./29_data_mem/*.csv \
       ./27_deadlock2/*.csv \
       ./28_json2/*.csv \
       ./26_env_set/*.csv \
       ./01_init_finalize/*.csv \
       ./02_task_depend/*.csv \
       ./02_task_depend/*.html \
       ./03_release/*.csv \
       ./04_enclosing_targets/*.csv \
       ./06_device/*.csv \
       ./07_policy_register/*.csv \
       ./08_multithreading/*.csv \
       ./09_dataflow/*.csv \
       ./10_multikernelexecution/*.csv \
       ./13_hooks/*.csv \
       ./14_permanent_task/*.csv \
       ./15_graph/*.csv \
       ./16_task_host/*.csv \
       ./17_json/*.csv \
       ./18_record/*.csv \
       ./19_replay/*.csv \
       ./21_task_malloc/*.csv \
       ./22_json_mixed_args/*.csv \
       ./23_multigraph/*.csv \
       ./24_multi_kernels/*.csv \
       ./25_random_tasks/*.csv \
       ./26_env_set/*.csv \
       ./29_data_mem/*.csv \
       ./31_isaxpy/*.csv \
       ./35_json_mixed_args_record_replay/*.csv \
       ./36_double_json_mixed_args_record_replay/*.csv 
