#ifndef BRINSBANE_INCLUDE_BRISBANE_BRISBANE_ERRNO_H
#define BRINSBANE_INCLUDE_BRISBANE_BRISBANE_ERRNO_H

#define BRISBANE_OK              0
#define BRISBANE_ERR            -1

#endif /* BRINSBANE_INCLUDE_BRISBANE_BRISBANE_ERRNO_H */

