#ifndef BRISBANE_INCLUDE_BRISBANE_HEXAGON_IMP_H
#define BRISBANE_INCLUDE_BRISBANE_HEXAGON_IMP_H

#define BRISBANE_HEXAGON_KERNEL_ARGS     int32 _off, int32 _ndr
#define BRISBANE_HEXAGON_KERNEL_BEGIN(i) for (i = _off; i < _off + _ndr; i++) {
#define BRISBANE_HEXAGON_KERNEL_END      }

#endif /* BRISBANE_INCLUDE_BRISBANE_HEXAGON_IMP_H */

