#ifndef BRISBANE_INCLUDE_BRISBANE_BRISBANE_ERRNO_H
#define BRISBANE_INCLUDE_BRISBANE_BRISBANE_ERRNO_H

#define BRISBANE_OK              0
#define BRISBANE_ERR            -1

#endif /* BRISBANE_INCLUDE_BRISBANE_BRISBANE_ERRNO_H */

